# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'SimplePlayer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SnapKit', '~> 4.0', :inhibit_warnings => true

end
